---
    version: "2"
    services:
      yeetgif:
        build:
            context: .
        container_name: yeetgif
        volumes:
            - ./in:/go/img-in
            - ./out:/go/img-out
            - ./make-gif.sh:/go/make-gif.sh
        command: ["./make-gif.sh", "${image_file}", "${gif_command}"]